# This file is used for Gradle options, for the rest use stonecutter.properties.toml
org.gradle.jvmargs=-Xmx3G
org.gradle.parallel=true
org.gradle.configuration-cache=false

mod.id=syrup_library
mod.name=Syrup Library
mod.group=net.syrupstudios
mod.version=0.2.0
mod.description=The Syrup Studio Library Mod.
mod.authors=SodaSyrup
mod.license=RSL-1.0

# Distribution publishing. Put API tokens in ~/.gradle/gradle.properties or
# use the CURSEFORGE_TOKEN and MODRINTH_TOKEN environment variables.
publish.curseforge_project_id=1647641
publish.modrinth_project_id=9tBNzmjo
publish.release_type=beta

deps.minecraft=[VERSIONED]
deps.java_version=[VERSIONED]
deps.fabric_loader=[VERSIONED]
deps.fabric_api=[VERSIONED]
deps.json5=3.0.0
deps.forge_version=[VERSIONED]
deps.neoforge_version=[VERSIONED]
