modLoader="javafml"
loaderVersion="[${forge},)"
license="${license}"

[[mods]]
modId="${modId}"
version="${version}"
displayName="${modName}"
authors="${authors}"
description='''${modDescription}'''

[[dependencies.${modId}]]
modId="minecraft"
mandatory=true
versionRange="${mc}"
ordering="NONE"
side="BOTH"
