modLoader="javafml"
loaderVersion="[1,)"
license="${license}"

[[mods]]
modId="${modId}"
version="${version}"
displayName="${modName}"
authors="${authors}"
description='''${modDescription}'''

[[dependencies.${modId}]]
modId="minecraft"
type="required"
versionRange="${mc}"
ordering="NONE"
side="BOTH"
